### ISSUE TITLE
Google搜不到这个仓库 很神奇

### ISSUE THREAD

**Issue by rintrint** [bb-yi/mmd-Quick-tool#1]
bing第一个就是了，google却完全搜不到，第一次遇到这种情况
https://www.bing.com/search?q=mmd-Quick-tool
https://www.google.com/search?q=mmd-Quick-tool

**Comment by bb-yi** [comment]
![image](https://github.com/bb-yi/mmd-Quick-tool/assets/55893863/ad575449-794f-4722-b8ea-cba38456a587)
 现在可以搜到了，搜索可能有时候抽风了

**Comment by fmnijk** [comment]
好耶
