### ISSUE TITLE
为肩膀手臂添加骨骼约束修正

### ISSUE THREAD

**Issue by ssbroad** [bb-yi/mmd-Quick-tool#2]
这个插件解决了长期以来blender导入vmd动作IK不匹配的痛点，配合烘焙物理简直神器

但是目前blender导入vmd依然存在一些问题

![MMD-3](https://github.com/user-attachments/assets/f41bbf6c-7a0d-4abc-8877-792ad66143a3)
![MMD-1](https://github.com/user-attachments/assets/97b9601a-b2d6-4f19-be2f-b62196a147bd)

可以看到在MMD中，手臂旋转没有大问题
但是到了blender中后，手臂却扭成了麻花状

**Comment by bb-yi** [comment]
手部动作不一样以前确实遇到过，没找到是什么造成的，不过也可以解决
原因之一可能是没有装配SDEF（这个装配之后可能有bug）
![image](https://github.com/user-attachments/assets/d2c386a8-26f6-48f7-86b9-f06e6addc7bc)

解决方法就是和腿部ik是一样的，先姿态模式选中身体骨骼（动作不一样的骨骼，我遇到这种情况一般会把所有身体骨骼都选上，除了手指骨骼）然后再去生成骨骼物体![image](https://github.com/user-attachments/assets/6d27e50f-ab63-4373-843d-8c5fde0d19ff)，接着按照流程去做就可以保证动作和mmd（abc）的完全一致了
